Traceback (most recent call last):
  File "/scratch1/05515/bflynn/UKB_knee_segmentation/joint_space.py", line 181, in <module>
    data = runner(lines, path, df)
  File "/scratch1/05515/bflynn/UKB_knee_segmentation/joint_space.py", line 164, in runner
    js = get_joint_space(femur, tibia)
  File "/scratch1/05515/bflynn/UKB_knee_segmentation/joint_space.py", line 101, in get_joint_space
    y_qb = y[quad_b][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
